<?xml version="1.0" encoding="utf-8"?><Database Name="dm76_5" Class="BalderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=balder.ucn.dk;Initial Catalog=dm76_5;Persist Security Info=True;User ID=DM76_5" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="dm76_5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Credentials" Member="Credentials">
    <Type Name="Credential">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Salt" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Association Name="User_Credential" Member="User" ThisKey="UserID" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="User_Credential" Member="Credential" ThisKey="UserId" OtherKey="UserID" Type="Credential" Cardinality="One" />
      <Association Name="User_ShoppingListsUser" Member="ShoppingListsUsers" ThisKey="UserId" OtherKey="UserId" Type="ShoppingListsUser" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Product_ShoppingListsProduct" Member="ShoppingListsProducts" ThisKey="ProductId" OtherKey="ProductsId" Type="ShoppingListsProduct" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingList" Member="ShoppingLists">
    <Type Name="ShoppingList">
      <Column Name="ShoppingListId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShoppingListName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompletionDate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ShoppingList_ShoppingListsProduct" Member="ShoppingListsProducts" ThisKey="ShoppingListId" OtherKey="ShoppingListId" Type="ShoppingListsProduct" />
      <Association Name="ShoppingList_ShoppingListsUser" Member="ShoppingListsUser" ThisKey="ShoppingListId" OtherKey="ShoppingListId" Type="ShoppingListsUser" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingListsProduct" Member="ShoppingListsProducts">
    <Type Name="ShoppingListsProduct">
      <Column Name="ShoppingListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ShoppingList_ShoppingListsProduct" Member="ShoppingList" ThisKey="ShoppingListId" OtherKey="ShoppingListId" Type="ShoppingList" IsForeignKey="true" />
      <Association Name="Product_ShoppingListsProduct" Member="Product" ThisKey="ProductsId" OtherKey="ProductId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingListsUser" Member="ShoppingListsUsers">
    <Type Name="ShoppingListsUser">
      <Column Name="ShoppingListId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_ShoppingListsUser" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="ShoppingList_ShoppingListsUser" Member="ShoppingList" ThisKey="ShoppingListId" OtherKey="ShoppingListId" Type="ShoppingList" IsForeignKey="true" />
    </Type>
  </Table>
</Database>